### ISSUE TITLE
Interact in RT with EtherCAT | I/O

### ISSUE THREAD

**Issue by jjrbfi** [grotius-cnc/hal-core#15]
Interact with the terminals in RT will be a plus.
Getting values and also changing them.

(Not sure if _halcmd_ will be the way to go. At least in realtime)

[Edit]
EtherCAT or whatever other terminal connected into HAL.

[Edit]
Good source to reach the goal? [http://linuxcnc.org/docs/ja/html/man/man3/](http://linuxcnc.org/docs/ja/html/man/man3/).

**Comment by grotius-cnc** [comment]
Hi,

If i look here http://wiki.ros.org/rostopic, i suggest this is a commandline style that you can use : 

$ rostopic pub -r 10 /cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.1, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}'
$ rostopic pub -r 10 /cmd_vel geometry_msgs/Twist  '{linear:  {x: 200.1, y: 200.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}

In above example you did 2 moves. I imagine the above commands are passed to a hal-core "c struct" that contains
a list of positions to do. 

Easyer is to pass it to the c++ side of the hal-core component as this can handle vectors easy. Using vectors in C is quite more work to setup with allocating, de-allocating etc.
The c++ side then gives the pos info to the c struct as a single line pos command and reports back when the move is done.

Then hal-core uses the stepgen component to perform the moves. You can report back your encoder pos every 1ms or even faster if you pass values back on the base-thread.

The stepgen component is the interpolation mechanisme to ensure your motors run very shooth without shocking because of time delays. The ruckig component is a s-curve style motion but has no stepgen pulse generator.
But you can combine these 2 easy.

Ros commands -> Your-hal-realtime-interface-component -> Ruckig.so -> Stepgen.so -> Lcec.so
or:
Ros commands -> Your-hal-realtime-interface-component ->  Stepgen.so -> Lcec.so

* What do you think?
I always have been thinking why need ros? Our technology don't really need ros. If you tell me your application i can maybe
give u some usefull examples.

**Comment by jjrbfi** [comment]
Hi,

Our idea using ROS is to interact with the iCIM robot we have with the EtherCAT terminals. (Read/Write values and set values to the motor encoder to go to whatever position [EL7342])

Right now ROS, is used in researchs as well as a "robot system standard" in many companies.
So I guess that if ROS is wrapped into/with HAL, LinuxCNC will be used more in companies that they already have EtherCAT with some proprietaries software.

Same with universities, that are using some software **non open source** that cost quite a lot and because of the cost, that can't be an option for schools/universities in different countries.


At this point I'm a bit more familiar with HAL and the commands it uses and looks great and works pretty good. But to interact with Gazebo for example, things go a bit more complicated if we use just halcmd commands for example.

 
My idea at begging was to interact directly with the drivers as I have used before here: [rtt_soem](https://github.com/keivanzavari/rtt_soem/tree/master/soem_beckhoff_drivers/src) (Different EtherCAT master)

But seems to me easier to interact with HAL and them get other drivers compatible with the same approach.

**Comment by jjrbfi** [comment]
Real-time is enabled since #18 Merge.

Looking forward to interact with it in real-time and them be able to use ROS at some point with it.
